import test from 'node:test';
import assert from 'node:assert/strict';
import {compileProject} from '../src/language/compiler.js';
import {VirtualMachine} from '../src/runtime/vm.js';
const project=code=>({name:'Debug',startup:'Sub Main',modules:[{name:'M',kind:'module',code}]});
async function paused(code,line){const p=project(code),output=[];const vm=new VirtualMachine(compileProject(p),{print:s=>output.push(s)});vm.setBreakpoint('M',line);let release;const stopped=new Promise(resolve=>release=resolve);const off=vm.on('pause',e=>{off();release(e);});const running=vm.start();await stopped;return {vm,p,output,running};}
test('pause listeners can resume synchronously without a lost resolver',async()=>{const vm=new VirtualMachine(compileProject(project('Sub Main()\nDebug.Print 1\nEnd Sub')));vm.on('pause',()=>vm.resume());await vm.start({breakOnEntry:true});assert.equal(vm.state,'running');});
test('active expression edit applies before the suspended instruction, retaining locals',async()=>{const code='Sub Main()\nDim n As Long\nn = 10\nn = n + 1\nDebug.Print n\nEnd Sub';const {vm,p,output,running}=await paused(code,4);p.modules[0].code=code.replace('n = n + 1','n = n + 5');const result=vm.applyEdits(p);assert.equal(result.revision,1);vm.resume();await running;assert.deepEqual(output,['15']);});
test('inserted comments remap breakpoints and current source without restarting',async()=>{const code='Sub Main()\nDim n As Long\nn = 5\nDebug.Print n\nEnd Sub';const {vm,p,output,running}=await paused(code,4);p.modules[0].code="'new header\n"+code;vm.applyEdits(p);assert.equal(vm.currentFrame.proc.code[vm.currentFrame.pc].line,5);assert.equal([...vm.breakpoints.values()][0].line,5);vm.resume();await running;assert.deepEqual(output,['5']);});
test('invalid syntax rejects atomically and leaves the old code runnable',async()=>{const code='Sub Main()\nDebug.Print 1\nEnd Sub';const {vm,p,output,running}=await paused(code,2);p.modules[0].code='Sub Main()\nIf True Then\nEnd Sub';assert.throws(()=>vm.applyEdits(p),/not applied/);assert.equal(vm.program.modules.get('m').source,code);vm.resume();await running;assert.deepEqual(output,['1']);});
test('active topology and local type edits require restart without losing locals',async()=>{const code='Sub Main()\nDim n As Long\nn = 10\nDebug.Print n\nEnd Sub';const {vm,p,output,running}=await paused(code,4);for(const replacement of [code.replace('Long','String'),code.replace('Debug.Print n','For n = 1 To 2\nDebug.Print n\nNext')]){p.modules[0].code=replacement;assert.throws(()=>vm.applyEdits(p),/Restart required/);assert.equal(vm.currentFrame.locals.get('n').get(),10);}vm.resume();await running;assert.deepEqual(output,['10']);});
test('module fields, signatures and deleted procedures are rejected atomically',async()=>{const code='Private total As Long\nSub Main()\nDebug.Print 1\nEnd Sub\nSub Other()\nEnd Sub';const {vm,p,running}=await paused(code,3);for(const replacement of [code.replace('total As Long','total As String'),code.replace('Other()','Other(x As Long)'),code.replace('Sub Other()\nEnd Sub','')]){p.modules[0].code=replacement;assert.throws(()=>vm.applyEdits(p),/Restart required/);}vm.resume();await running;});
test('inactive procedure bodies can change control flow and new procedures can be added',async()=>{const code='Sub Main()\nWork\nEnd Sub\nSub Work()\nDebug.Print 1\nEnd Sub';const {vm,p,output,running}=await paused(code,2);p.modules[0].code='Sub Main()\nWork\nEnd Sub\nSub Work()\nDim i As Long\nFor i = 1 To 3\nPrintOne i\nNext\nEnd Sub\nSub PrintOne(n As Long)\nDebug.Print n\nEnd Sub';vm.applyEdits(p);vm.resume();await running;assert.deepEqual(output,['1','2','3']);});
test('edits update existing class instances and held procedure identities',async()=>{const p=project('Dim thing As Counter\nSub Main()\nSet thing = New Counter\nthing.Go\nEnd Sub');p.modules.push({name:'Counter',kind:'class',code:'Sub Go()\nDebug.Print 1\nEnd Sub'});const output=[],vm=new VirtualMachine(compileProject(p),{print:s=>output.push(s)});vm.setBreakpoint('M',4);let resolve;const pause=new Promise(r=>resolve=r);const off=vm.on('pause',()=>{off();resolve();});const running=vm.start();await pause;const original=vm.program.modules.get('counter').procedures.get('go');p.modules[1].code='Sub Go()\nDebug.Print 9\nEnd Sub';vm.applyEdits(p);assert.equal(vm.program.modules.get('counter').procedures.get('go'),original);vm.resume();await running;assert.deepEqual(output,['9']);});
test('all suspended caller frames are validated, not only the top frame',async()=>{const code='Sub Main()\nWorker\nDebug.Print 2\nEnd Sub\nSub Worker()\nDebug.Print 1\nEnd Sub';const {vm,p,output,running}=await paused(code,6);p.modules[0].code=code.replace('Worker\nDebug.Print 2','Worker\nFor i = 1 To 2\nDebug.Print 2\nNext');assert.throws(()=>vm.applyEdits(p),/active procedure/);vm.resume();await running;assert.deepEqual(output,['1','2']);});
test('Set Next Statement skips a pending statement in a straight-line region',async()=>{const {vm,output,running}=await paused('Sub Main()\nDebug.Print "skip"\nDebug.Print "keep"\nEnd Sub',2);assert.equal(vm.setNextStatement('M',3).line,3);vm.resume();await running;assert.deepEqual(output,['keep']);});
test('Set Next Statement can replay an assignment while retaining state',async()=>{const {vm,output,running}=await paused('Sub Main()\nDim n As Long\nn = n + 1\nDebug.Print n\nEnd Sub',4);vm.setNextStatement('M',3);vm.breakpoints.clear();vm.resume();await running;assert.deepEqual(output,['2']);});
test('Set Next Statement rejects cross-procedure, cross-module and loop-entry moves',async()=>{const {vm,running}=await paused('Sub Main()\nDim i As Long\nDebug.Print 1\nFor i = 1 To 2\nDebug.Print i\nNext\nEnd Sub\nSub Other()\nDebug.Print 9\nEnd Sub',3);assert.throws(()=>vm.setNextStatement('Other',3));assert.throws(()=>vm.setNextStatement('M',9));assert.throws(()=>vm.setNextStatement('M',5),/control-flow/);assert.throws(()=>vm.setNextStatement('M',1));vm.resume();await running;});
test('running non-paused frames cannot receive unsafe debugger mutations',async()=>{const p=project('Sub Main()\nEnd Sub'),vm=new VirtualMachine(compileProject(p));assert.throws(()=>vm.setNextStatement('M',2),/break mode/);assert.throws(()=>vm.applyEdits(p),/Pause execution/);});
