import {readRES,writeRES} from './res.js';
import {newId,createForm,newProject,normalizeProject} from './model.js';
import {lower} from '../core/core.js';
import {VBError} from '../language/lexer.js';
import {decodeANSI,encodeANSI} from '../runtime/binary-codec.js';
import {cleanProjectPath,relativeProjectPath,resolveProjectPath,hydrateResources,prepareResources,toBase64} from './frx.js';
export function parseVBValue(value){
  let quoted=false;for(let i=0;i<value.length;i++){if(value[i]==='"'){if(quoted&&value[i+1]==='"'){i++;continue;}quoted=!quoted;}else if(value[i]==="'"&&!quoted){value=value.slice(0,i);break;}}
  value=value.trim();const match=value.match(/^(\$?)"((?:[^"]|"")*)"(.*)$/);if(match){const name=match[2].replace(/""/g,'"'),tail=match[3].trim();return tail?{resource:name,offset:tail.replace(/^:\s*/,''),...(match[1]?{text:true}:{})}:name;}
  if(/^&H/i.test(value)){let n=parseInt(value.slice(2).replace(/&$/,''),16);if(n>2147483647)n-=4294967296;return n;}if(/^[+-]?\d+(\.\d+)?$/.test(value))return Number(value);if(/^True$/i.test(value))return -1;if(/^False$/i.test(value))return 0;return value;
}
export function serializeVBValue(value){if(typeof value==='string')return '"'+value.replace(/"/g,'""')+'"';if(typeof value==='boolean')return value?'-1':'0';if(value?.resource)return (value.text?'$':'')+'"'+value.resource.replace(/"/g,'""')+'":'+value.offset;return String(value??0);}
const fontKeys={Name:'FontName',Size:'FontSize',Weight:'FontWeight',Charset:'FontCharset',Italic:'FontItalic',Underline:'FontUnderline',Strikethrough:'FontStrikethrough'};
function splitAttributes(lines){const attributes=lines.filter(line=>/^Attribute\s+/i.test(line.trim())).map(l=>l.trim()),code=lines.filter(line=>!/^Attribute\s+/i.test(line.trim())).join('\n').trim()+'\n';return {attributes,code};}
function nativeCode(module,defaults=[]){
  const attributes=module.attributes||defaults,moduleAttributes=attributes.filter(a=>!/^Attribute\s+\w+\./i.test(a)&&!/^Attribute\s+VB_Name\b/i.test(a)),memberAttributes=attributes.filter(a=>/^Attribute\s+\w+\./i.test(a));
  const lines=[`Attribute VB_Name = "${module.name}"`,...moduleAttributes],code=module.code.replace(/\r\n?/g,'\n').trim().split('\n');
  for(const line of code){lines.push(line);const m=line.match(/^\s*(?:(?:Public|Private|Friend|Static)\s+)*(?:Sub|Function|Property\s+(?:Get|Let|Set))\s+(\w+)/i);if(m)for(const attribute of memberAttributes)if(lower(attribute.match(/^Attribute\s+(\w+)\./i)[1])===lower(m[1]))lines.push(attribute);}
  return lines.join('\r\n');
}
export function parseFRM(text,fileName='Form1.frm'){
  const lines=text.replace(/\r\n?/g,'\n').split('\n'),module=createForm(fileName.split(/[\\/]/).at(-1).replace(/\.frm$/i,'')),stack=[],groups=[],diagnostics=[];let rootSeen=false,rootEnded=false,codeStart=lines.length;module.form.controls=[];module.form.menus=[];module.nativeHeaders=[];
  for(let i=0;i<lines.length;i++){const line=lines[i].trim();let m;if(rootEnded){codeStart=i;break;}
    if(/^VERSION\b/i.test(line)||/^Object\s*=/i.test(line)){module.nativeHeaders.push(line);continue;}if(!line)continue;
    if((m=line.match(/^Begin\s+([\w.]+)\s+(\w+)$/i))){if(groups.length)throw new VBError('Control declaration inside a property group',1002);const type=m[1].split('.').at(-1),node={id:newId(),name:m[2],type,originalType:m[1],parent:stack.length>1?stack.at(-1).name:null,properties:{Name:m[2]},propertyGroups:[]};if(!rootSeen){module.name=m[2];module.form={...node,controls:[],menus:[]};rootSeen=true;stack.push(module.form);}else{if(type==='Menu'){module.form.menus.push(node);node.parent=stack.at(-1)?.type==='Menu'?stack.at(-1).name:null;}else module.form.controls.push(node);stack.push(node);}continue;}
    if((m=line.match(/^BeginProperty\s+(\w+)(.*)$/i))){if(!stack.length)throw new VBError('Property group outside a control',1002);const group={name:m[1],suffix:m[2],entries:[],groups:[]};(groups.length?groups.at(-1).groups:stack.at(-1).propertyGroups).push(group);groups.push(group);continue;}
    if(/^EndProperty$/i.test(line)){if(!groups.length)throw new VBError('Unexpected EndProperty',1002);groups.pop();continue;}
    if(/^End$/i.test(line)){if(groups.length)throw new VBError('Unterminated property group',1002);stack.pop();if(!stack.length&&rootSeen)rootEnded=true;continue;}
    if((m=line.match(/^(\w+(?:\(\d+\))?)\s*=\s*(.*)$/))&&stack.length){if(/^(?:__proto__|prototype|constructor)$/i.test(m[1]))throw new VBError('Unsafe property name',1002);const value=parseVBValue(m[2]),node=stack.at(-1);if(groups.length){const path=groups.map(g=>g.name).join('.'),key=path==='Font'?fontKeys[m[1]]||'Font'+m[1]:path+'.'+m[1];groups.at(-1).entries.push({name:m[1],key});node.properties[key]=value;if(path==='Font'&&m[1]==='Weight')node.properties.FontBold=Number(value)>=700?-1:0;}else node.properties[m[1]]=value;}
  }
  if(!rootSeen)throw new VBError('No Begin VB.Form declaration found in '+fileName,1002);if(!rootEnded)throw new VBError('Unterminated form declaration in '+fileName,1002);
  Object.assign(module,splitAttributes(lines.slice(codeStart)),{kind:'form',id:newId(),sourcePath:cleanProjectPath(fileName)});return {module,diagnostics};
}
export function serializeFRM(module){
  const lines=module.nativeHeaders?.length?[...module.nativeHeaders]:['VERSION 5.00'],form=module.form;
  const write=(node,depth)=>{const indent='   '.repeat(depth),type=node.originalType||(['Form','MDIForm','Menu','PictureBox','Label','TextBox','Frame','CommandButton','CheckBox','OptionButton','ComboBox','ListBox','HScrollBar','VScrollBar','Timer','DriveListBox','DirListBox','FileListBox','Shape','Line','Image','Data','OLE'].includes(node.type)?'VB.'+node.type:node.type);lines.push(`${indent}Begin ${type} ${node.name}`);
    for(const [key,value]of Object.entries(node.properties||{})){if(key==='Name'||key.startsWith('Font')||key.includes('.')||['List','GridData','Nodes','Columns','Items','Tabs','Panels','Buttons'].includes(key)&&!value?.resource||typeof value==='object'&&!value?.resource)continue;lines.push(`${indent}   ${key.padEnd(16)}=   ${serializeVBValue(value)}`);}
    const writeGroup=(g,level)=>{const tab='   '.repeat(level);lines.push(`${tab}BeginProperty ${g.name}${g.suffix||''}`);for(const e of g.entries){const value=node.properties[e.key];if(value!==undefined)lines.push(`${tab}   ${e.name.padEnd(16)}=   ${serializeVBValue(e.key==='FontWeight'&&node.properties.FontBold!==undefined?(node.properties.FontBold?700:400):value)}`);}for(const child of g.groups)writeGroup(child,level+1);lines.push(tab+'EndProperty');};
    const groups=node.propertyGroups||[];for(const group of groups)writeGroup(group,depth+1);
    if(node.properties.FontName&&!groups.some(g=>g.name==='Font')){lines.push(`${indent}   BeginProperty Font`,`${indent}      Name            =   ${serializeVBValue(node.properties.FontName)}`,`${indent}      Size            =   ${node.properties.FontSize||8.25}`,`${indent}      Charset         =   ${node.properties.FontCharset||0}`,`${indent}      Weight          =   ${node.properties.FontBold?700:400}`,`${indent}      Underline       =   ${node.properties.FontUnderline||0}`,`${indent}      Italic          =   ${node.properties.FontItalic||0}`,`${indent}      Strikethrough   =   ${node.properties.FontStrikethrough||0}`,`${indent}   EndProperty`);}
    for(const c of form.controls.filter(c=>(c.parent||null)===(node===form?null:node.name)))write(c,depth+1);for(const c of form.menus.filter(c=>(c.parent||null)===(node===form?null:node.name)))write(c,depth+1);lines.push(indent+'End');
  };write(form,0);lines.push(nativeCode(module,['Attribute VB_GlobalNameSpace = False','Attribute VB_Creatable = False','Attribute VB_PredeclaredId = True','Attribute VB_Exposed = False']));return lines.join('\r\n')+'\r\n';
}
export function parseCodeModule(text,fileName){const name=text.match(/^Attribute\s+VB_Name\s*=\s*"([^"]+)"/im)?.[1]||fileName.split(/[\\/]/).at(-1).replace(/\.(bas|cls)$/i,''),kind=/\.cls$/i.test(fileName)?'class':'module';let code=text.replace(/\r\n?/g,'\n'),nativeClassHeader;
  if(kind==='class'){const wrapper=code.match(/^VERSION[^\n]*\nBEGIN[\s\S]*?^END\s*\n/im);if(wrapper){nativeClassHeader=wrapper[0].trim();code=code.replace(wrapper[0],'');}}
  return {id:newId(),name,kind,...splitAttributes(code.split('\n')),sourcePath:cleanProjectPath(fileName),...(nativeClassHeader?{nativeClassHeader}:{})};
}
export function parseVBP(text){const meta={name:'Project1',startup:'Form1',files:[],references:[],settings:{},raw:{},rawEntries:[]};for(const line of text.replace(/\r\n?/g,'\n').split('\n')){const at=line.indexOf('=');if(at<0)continue;const key=line.slice(0,at).trim(),value=line.slice(at+1).trim(),k=key.toLowerCase();if(k==='form')meta.files.push({kind:'form',path:value.replace(/^"|"$/g,'')});else if(k==='module'||k==='class'){const sep=value.indexOf(';'),name=(sep<0?value:value.slice(0,sep)).trim(),path=(sep<0?value:value.slice(sep+1)).trim().replace(/^"|"$/g,'');meta.files.push({kind:k==='module'?'module':'class',name,path});}else if(k==='name')meta.name=parseVBValue(value);else if(k==='startup')meta.startup=parseVBValue(value);else if(k==='reference'||k==='object')meta.references.push({kind:k==='reference'?'Reference':'Object',value});else{meta.raw[key]=value;meta.rawEntries.push({key,value});}}return meta;}
function modulePath(m){return m.sourcePath||m.name+(m.kind==='form'?'.frm':m.kind==='class'?'.cls':'.bas');}
export function serializeVBP(project){const native=project.nativeProject||{},owner=native.path||project.name+'.vbp',raw=(native.entries||[]).filter(e=>!project.resources||e.key.toLowerCase()!=='resfile32'),lines=raw.length?raw.map(e=>e.key+'='+e.value):['Type=Exe','MajorVer=0','MinorVer=2','RevisionVer=0','AutoIncrementVer=0'];for(const m of project.modules){const path=relativeProjectPath(owner,modulePath(m));lines.push(m.kind==='form'?`Form=${path}`:`${m.kind==='class'?'Class':'Module'}=${m.name}; ${path}`);}if(project.resources)lines.push('ResFile32="'+relativeProjectPath(owner,project.resources.fileName)+'"');for(const r of project.references||[])lines.push(`${r.kind}=${r.value}`);lines.push(`Startup="${project.startup}"`,`Name="${project.name}"`);if(!raw.some(e=>e.key.toLowerCase()==='title'))lines.push(`Title="${project.name}"`);return lines.join('\r\n')+'\r\n';}
export function sourceFiles(project){const prepared=prepareResources(project),files={...prepared.files},owner=project.nativeProject?.path||project.name+'.vbp';if(project.resources)files[cleanProjectPath(project.resources.fileName)]=writeRES(project.resources);files[cleanProjectPath(owner)]=serializeVBP({...project,modules:prepared.modules});for(const m of prepared.modules){let source;if(m.kind==='form')source=serializeFRM(m);else source=(m.kind==='class'?(m.nativeClassHeader||'VERSION 1.0 CLASS\nBEGIN\n  MultiUse = -1\nEND').replace(/\r\n?/g,'\n').replace(/\n/g,'\r\n')+'\r\n':'')+nativeCode(m)+'\r\n';files[cleanProjectPath(modulePath(m))]=m.sourceEncoding==='windows-1252'?encodeANSI(source):source;}return files;}
export async function importFiles(entries){
  const normalized=new Map(),caseNames=new Set();for(const [name,data]of entries){const path=cleanProjectPath(name),key=path.toLowerCase();if(caseNames.has(key))throw new VBError('Duplicate case-insensitive project path: '+name,1002);caseNames.add(key);normalized.set(path,data);}
  const diagnostics=[];let sourceEncoding='utf-8';const text=data=>{sourceEncoding='utf-8';if(typeof data==='string')return data;try{return new TextDecoder('utf-8',{fatal:true}).decode(data);}catch{sourceEncoding='windows-1252';if(!diagnostics.some(d=>d.source==='Import'))diagnostics.push({severity:'warning',source:'Import',message:'Non-UTF-8 source decoded as Windows-1252; that source encoding will be used for native export.'});return decodeANSI(data);}};
  const json=[...normalized].find(([n])=>/\.(vb6web|vb6proj|json)$/i.test(n));if(json){try{return {project:normalizeProject(JSON.parse(text(json[1]))),diagnostics:[]};}catch(error){if(!/\.json$/i.test(json[0]))throw error;}}
  const vbp=[...normalized].find(([n])=>/\.vbp$/i.test(n)),meta=vbp?parseVBP(text(vbp[1])):null,project=newProject(meta?.name||'ImportedProject');project.modules=[];project.references=meta?.references||[];if(meta)project.nativeProject={path:vbp[0],entries:meta.rawEntries};
  let relevant=[];if(meta){const seen=new Set();for(const file of meta.files){let path;try{path=resolveProjectPath(normalized.keys(),vbp[0],file.path,{basenameFallback:true});}catch(error){diagnostics.push({severity:'error',source:meta.name,message:error.message});continue;}if(!path){diagnostics.push({severity:'error',source:meta.name,message:'Missing referenced source file: '+file.path});continue;}if(!seen.has(path)){seen.add(path);relevant.push([path,normalized.get(path)]);}}}else relevant=[...normalized].filter(([n])=>/\.(frm|bas|cls)$/i.test(n));
  const consumed=new Set(vbp?[vbp[0]]:[]);for(const [path,data]of relevant){const contents=text(data),encoding=sourceEncoding;let module;if(/\.frm$/i.test(path)){const parsed=parseFRM(contents,path);module=parsed.module;diagnostics.push(...parsed.diagnostics);}else if(/\.(bas|cls)$/i.test(path))module=parseCodeModule(contents,path);else{diagnostics.push({severity:'error',source:project.name,message:'Unsupported source type: '+path});continue;}module.sourceEncoding=encoding;project.modules.push(module);consumed.add(path);}
  if(!project.modules.length)throw new VBError('No .vb6web project or referenced .frm/.bas/.cls source files were found. Select the .vbp and all referenced source files together.',1002);
  project.startup=meta?.startup||project.modules.find(m=>m.kind==='form')?.name||'Sub Main';
  const resourceReference=meta?.rawEntries.find(e=>e.key.toLowerCase()==='resfile32');
  if(resourceReference){const ref=parseVBValue(resourceReference.value),path=resolveProjectPath(normalized.keys(),vbp[0],ref,{basenameFallback:true});if(!path)diagnostics.push({severity:'error',source:project.name,message:'Missing referenced resource file: '+ref});else{const data=normalized.get(path);if(typeof data==='string')throw new VBError('Native .res import requires binary bytes',1002);project.resources=readRES(data,path);consumed.add(path);}}
  for(const [path,data]of normalized)if(!consumed.has(path)){const bytes=typeof data==='string'?new TextEncoder().encode(data):new Uint8Array(data);project.assets[path]={encoding:'base64',data:toBase64(bytes)};}
  hydrateResources(project,diagnostics);for(const r of project.references)diagnostics.push({severity:'warning',source:project.name,message:'Native reference retained; browser reimplementation required: '+r.value});
  if(meta?.raw.Type&&!/^Exe$/i.test(meta.raw.Type))diagnostics.push({severity:'warning',source:project.name,message:'Project type '+meta.raw.Type+' retained as metadata; native ActiveX executables/libraries are not generated.'});
  return {project:normalizeProject(project),diagnostics};
}
